[build]
command = "pnpm run build"
publish = "dist"

[images]
remote_images = ["https://gravatar.com/.*"]

[[redirects]]
from = "/index.html"
to = "/"
status = 301

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "https://thasmo.dev/*"
to = "https://thasmo.com/:splat"
status = 301

[[redirects]]
from = "https://www.thasmo.dev/*"
to = "https://thasmo.com/:splat"
status = 301

[[redirects]]
from = "https://deinhamer.at/*"
to = "https://thasmo.com/:splat"
status = 301

[[redirects]]
from = "https://www.deinhamer.at/*"
to = "https://thasmo.com/:splat"
status = 301

[[redirects]]
from = "https://deinhamer.com/*"
to = "https://thasmo.com/:splat"
status = 301

[[redirects]]
from = "https://www.deinhamer.com/*"
to = "https://thasmo.com/:splat"
status = 301
